// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onwelo.API.Database.Context;

#nullable disable

namespace Onwelo.API.Migrations
{
    [DbContext(typeof(OnweloDbContext))]
    partial class OnweloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Onwelo.API.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("Onwelo.API.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("Onwelo.API.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Voters", (string)null);
                });

            modelBuilder.Entity("Onwelo.API.Entities.Candidate", b =>
                {
                    b.HasOne("Onwelo.API.Entities.Person", "Person")
                        .WithOne("Candidate")
                        .HasForeignKey("Onwelo.API.Entities.Candidate", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Onwelo.API.Entities.Voter", b =>
                {
                    b.HasOne("Onwelo.API.Entities.Candidate", "Candidate")
                        .WithMany("Voters")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Onwelo.API.Entities.Person", "Person")
                        .WithOne("Voter")
                        .HasForeignKey("Onwelo.API.Entities.Voter", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Onwelo.API.Entities.Candidate", b =>
                {
                    b.Navigation("Voters");
                });

            modelBuilder.Entity("Onwelo.API.Entities.Person", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Voter");
                });
#pragma warning restore 612, 618
        }
    }
}
